language: cpp
dist: trusty
compiler: g++
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
  - sudo apt-get update

install:
  - sudo apt-get install qt55base
  - source /opt/qt55/bin/qt55-env.sh

script:
  - /opt/qt55/bin/qmake PREFIX=/usr
  - make
  
deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file: "Qontainer"
  skip_cleanup: true
  on:
    tags: true
